"""Manual Telegram bridge for ML Signal Overlay preview payloads.

PAPER_ONLY / READ_ONLY analytics helper. This script only reads the preview
JSON generated by ml_signal_overlay_v1.py and can send it through the existing
Telegram sender when explicit manual gates are enabled.
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from html import escape
from pathlib import Path
from typing import Any, Dict, Tuple

from config import config
from telegram import send_telegram_message

DEFAULT_PREVIEW_PATH = "logs/ml_signal_overlay_telegram_preview.json"
DEFAULT_RESULT_PATH = "logs/ml_overlay_telegram_send_result.json"
ALLOW_SEND_ENV = "ALLOW_OVERLAY_TELEGRAM_SEND"
REQUIRED_PAYLOAD_MARKERS = (
    "PAPER ONLY",
    "No broker API",
    "No live execution",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Safely preview or manually send ML Signal Overlay payloads to Telegram."
    )
    parser.add_argument(
        "--send",
        action="store_true",
        help="Request a Telegram send. Still requires all manual safety gates.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Never send; validate and write the result JSON only.",
    )
    parser.add_argument(
        "--preview-path",
        default=DEFAULT_PREVIEW_PATH,
        help=f"Path to overlay preview JSON (default: {DEFAULT_PREVIEW_PATH}).",
    )
    parser.add_argument(
        "--result-path",
        default=DEFAULT_RESULT_PATH,
        help=f"Path for send result JSON (default: {DEFAULT_RESULT_PATH}).",
    )
    return parser.parse_args()


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def read_preview_payload(preview_path: str) -> Tuple[Dict[str, Any], str | None]:
    path = Path(preview_path)
    try:
        with path.open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, json.JSONDecodeError) as exc:
        return {}, f"preview_read_failed: {exc}"

    if not isinstance(payload, dict):
        return {}, "preview_payload_not_object"
    return payload, None


def validate_safety(payload: Dict[str, Any]) -> Tuple[bool, str | None]:
    payload_text = payload.get("payload_text")
    checks = {
        "paper_only must be true": payload.get("paper_only") is True,
        "broker_api_enabled must be false": payload.get("broker_api_enabled") is False,
        "live_execution_enabled must be false": payload.get("live_execution_enabled") is False,
        "payload_text must be a string": isinstance(payload_text, str),
    }

    if isinstance(payload_text, str):
        for marker in REQUIRED_PAYLOAD_MARKERS:
            checks[f'payload_text missing "{marker}"'] = marker in payload_text

    failed = [reason for reason, passed in checks.items() if not passed]
    if failed:
        return False, "; ".join(failed)
    return True, None


def write_result(result_path: str, result: Dict[str, Any]) -> None:
    path = Path(result_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=2, sort_keys=True)
        handle.write("\n")


def build_result(
    *,
    args: argparse.Namespace,
    payload: Dict[str, Any],
    safety_passed: bool,
    send_attempted: bool,
    send_success: bool,
    send_blocked_reason: str | None,
) -> Dict[str, Any]:
    return {
        "generated_at": utc_now_iso(),
        "symbol": payload.get("symbol"),
        "preview_path": args.preview_path,
        "result_path": args.result_path,
        "safety_passed": safety_passed,
        "send_requested": bool(args.send),
        "dry_run": bool(args.dry_run),
        "send_attempted": send_attempted,
        "send_success": send_success,
        "send_blocked_reason": send_blocked_reason,
        "telegram_enabled": bool(config.telegram_enabled),
        "payload_text": payload.get("payload_text"),
    }


def determine_block_reason(
    *,
    args: argparse.Namespace,
    safety_passed: bool,
    safety_reason: str | None,
) -> str | None:
    if not safety_passed:
        return safety_reason or "safety validation failed"
    if args.dry_run:
        return "dry-run requested"
    if not args.send:
        return "send flag not passed; preview only"
    if os.getenv(ALLOW_SEND_ENV) != "1":
        return f"{ALLOW_SEND_ENV} not enabled"
    if not config.telegram_enabled:
        return "telegram not enabled"
    if not config.telegram_bot_token:
        return "telegram bot token missing"
    if not config.telegram_chat_id:
        return "telegram chat id missing"
    return None


def main() -> int:
    args = parse_args()
    payload, read_error = read_preview_payload(args.preview_path)
    safety_passed, safety_reason = validate_safety(payload)
    if read_error and safety_reason:
        safety_reason = f"{read_error}; {safety_reason}"
    elif read_error:
        safety_reason = read_error
        safety_passed = False

    send_blocked_reason = determine_block_reason(
        args=args,
        safety_passed=safety_passed,
        safety_reason=safety_reason,
    )
    send_attempted = False
    send_success = False

    if not safety_passed:
        print("Overlay Telegram Send: BLOCKED — safety validation failed")
    elif args.send and not args.dry_run and os.getenv(ALLOW_SEND_ENV) != "1":
        print(f"Overlay Telegram Send: BLOCKED — {ALLOW_SEND_ENV} not enabled")
    elif send_blocked_reason:
        print(f"Overlay Telegram Send: BLOCKED — {send_blocked_reason}")
    else:
        send_attempted = True
        send_success = send_telegram_message(
            bot_token=config.telegram_bot_token,
            chat_id=config.telegram_chat_id,
            message=escape(str(payload.get("payload_text", ""))),
            timeout=config.request_timeout_seconds,
        )
        print(
            "Overlay Telegram Send: SENT"
            if send_success
            else "Overlay Telegram Send: FAILED"
        )
        if not send_success:
            send_blocked_reason = "telegram send failed"

    result = build_result(
        args=args,
        payload=payload,
        safety_passed=safety_passed,
        send_attempted=send_attempted,
        send_success=send_success,
        send_blocked_reason=send_blocked_reason,
    )
    write_result(args.result_path, result)

    if not args.send or args.dry_run:
        payload_text = payload.get("payload_text")
        if isinstance(payload_text, str) and payload_text:
            print(payload_text)

    return 0 if (send_success or not send_attempted) else 1


if __name__ == "__main__":
    raise SystemExit(main())
